import os
import urllib.request
import json
from dotenv import load_dotenv

load_dotenv("d:/shajra system/.env")

AIRTABLE_PAT = os.environ.get("AIRTABLE_PAT")
AIRTABLE_BASE_ID = os.environ.get("AIRTABLE_BASE_ID")

def add_columns():
    url = f"https://api.airtable.com/v0/meta/bases/{AIRTABLE_BASE_ID}/tables"
    req = urllib.request.Request(url, method="GET")
    req.add_header("Authorization", f"Bearer {AIRTABLE_PAT}")
    
    try:
        res = urllib.request.urlopen(req)
        data = json.loads(res.read().decode())
        print("Successfully read schema!")
        tables = data.get("tables", [])
        
        pending_table_id = None
        approved_table_id = None
        
        for t in tables:
            if t["name"] == "PendingSubmissions":
                pending_table_id = t["id"]
            elif t["name"] == "ApprovedMembers":
                approved_table_id = t["id"]
                
        print(f"Pending ID: {pending_table_id}")
        print(f"Approved ID: {approved_table_id}")
        
        if pending_table_id:
            pending_fields = ["RawEmail", "RawPhoneNumber", "RawProfileImage", "CleanEmail", "CleanPhoneNumber", "CleanProfileImage"]
            for f in pending_fields:
                try:
                    f_url = f"https://api.airtable.com/v0/meta/bases/{AIRTABLE_BASE_ID}/tables/{pending_table_id}/fields"
                    f_req = urllib.request.Request(f_url, method="POST")
                    f_req.add_header("Authorization", f"Bearer {AIRTABLE_PAT}")
                    f_req.add_header("Content-Type", "application/json")
                    payload = json.dumps({"description": "Generated by Shajra API", "name": f, "type": "singleLineText"})
                    f_req.data = payload.encode("utf-8")
                    urllib.request.urlopen(f_req)
                    print(f"Created {f} in PendingSubmissions")
                except urllib.error.HTTPError as e:
                    print(f"Failed to create {f} in Pending: {e.read().decode()}")

        if approved_table_id:
            approved_fields = ["Email", "PhoneNumber", "ProfileImageUrl"]
            for f in approved_fields:
                try:
                    f_url = f"https://api.airtable.com/v0/meta/bases/{AIRTABLE_BASE_ID}/tables/{approved_table_id}/fields"
                    f_req = urllib.request.Request(f_url, method="POST")
                    f_req.add_header("Authorization", f"Bearer {AIRTABLE_PAT}")
                    f_req.add_header("Content-Type", "application/json")
                    
                    if f == "ProfileImageUrl":
                        payload = json.dumps({"description": "Generated by Shajra API", "name": f, "type": "url"})
                    else:
                        payload = json.dumps({"description": "Generated by Shajra API", "name": f, "type": "singleLineText"})
                        
                    f_req.data = payload.encode("utf-8")
                    urllib.request.urlopen(f_req)
                    print(f"Created {f} in ApprovedMembers")
                except urllib.error.HTTPError as e:
                    print(f"Failed to create {f} in Approved: {e.read().decode()}")

    except urllib.error.HTTPError as e:
        print(f"Schema Meta API failed: {e.read().decode()}")
        print("Your PAT does not have 'schema.bases:read' or 'schema.bases:write' permissions.")
        
add_columns()
